# Site settings

title: 'LA Referencia'
title_en: 'LA Referencia'
title_pt: 'LA Referencia'

description: 'Red Latinoamericana y de España de Ciencia Abierta.'

baseurl: ''
absolute_url: ''
url: ''

email: lareferencia@lareferencia.redclara.net
twitter_username: ''
github_username: ''

default_language: 'es'
fallback_page: 'home'

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
page_excerpts: true
excerpt_separator: <!--more-->
sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - slash-div

collections:
  pages:
    output: true
    permalink: /:path
  news:
    output: true
  members:
    output: true
  home_cards:
    output: false

# Post defaults by language
defaults:
-
  scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/:title'
    language: en
-
  scope:
    path: '_posts/es'
    type: 'posts'
  values:
    permalink: 'es/:title'
    language: es
-
  scope:
    path: '_posts/pt'
    type: 'posts'
  values:
    permalink: 'pt/:title'
    language: pt
-
  scope:
    path: '_news/en'
    type: 'news'
  values:
    permalink: 'en/news/:title'
    language: en
    layout: news
    published: true
-
  scope:
    path: '_news/es'
    type: 'news'
  values:
    permalink: 'es/news/:title'
    language: es
    layout: news
    published: true
-
  scope:
    path: '_news/pt'
    type: 'news'
  values:
    permalink: 'pt/news/:title'
    language: pt
    layout: news
    published: true
-
  scope:
    path: '_members/en'
    type: 'members'
  values:
    permalink: 'en/members/:title'
    language: en
    layout: member
    published: true
-
  scope:
    path: '_members/es'
    type: 'members'
  values:
    permalink: 'es/miembros/:title'
    language: es
    layout: member
    published: true
-
  scope:
    path: '_members/pt'
    type: 'members'
  values:
    permalink: 'pt/membros/:title'
    language: pt
    layout: member
    published: true
-
  scope:
    path: '_home_cards/en'
    type: 'home_cards'
  values:
    language: en
    published: true
    order: 999
-
  scope:
    path: '_home_cards/es'
    type: 'home_cards'
  values:
    language: es
    published: true
    order: 999
-
  scope:
    path: '_home_cards/pt'
    type: 'home_cards'
  values:
    language: pt
    published: true
    order: 999
